Algoritmo "calculoAreacirculo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/03/2022
Var
// Seção de Declarações das variáveis 
area,raio:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite o valor do raio")
leia(raio)
area<-raio*raio*3.14159
Escreval("O calculo da área é igual:",area)

Fimalgoritmo