Algoritmo "NUMERONEGATIVO"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/04/2022
Var
// Seção de Declarações das variáveis valor
valor:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Digite um número")
leia(valor)
se valor>=0 então
Escreval("Este número é positivo")
senão
Escreval("Este número é negativo")
fimse


Fimalgoritmo