Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/04/2022
Var
// Seção de Declarações das variáveis 
celcius:real
faren:real
contadora:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

repita
celcius<-celcius+10

faren<-(9*celcius+160)/5
Escreval("Temperatura em Graus Celcius:",celcius, " farennait:",faren)


até celcius>90
Fimalgoritmo